### ISSUE TITLE
Schema Design

### ISSUE THREAD

**Issue by see-k** [see-k/projectLasagna#1]

**Comment by qc2xt** [comment]
https://drive.google.com/file/d/1eko7VjkSz8kEvk4AXhXPK_cUQn_pVzyg/view?usp=sharing

**Comment by qc2xt** [comment]
https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1eko7VjkSz8kEvk4AXhXPK_cUQn_pVzyg%26export%3Ddownload
