### ISSUE TITLE
Database: DDL

### ISSUE THREAD

**Issue by qc2xt** [see-k/projectLasagna#10]
Time estimate: 2 hrs

- [x] Users
     - user_id char(36) (PK)
     - user_name varchar(25)
     - email varchar(50)
     - disabled boolean
- [x] Cats
     - cat_id int (PK)
     - user_id (FK)
     - name varchar(50)
     - img_path varchar(100)
     - cat_description varchar(300)
     - disabled boolean
- [x] Alias
     - alias_id int (PK)
     - cat_id (FK)
     - alias_name varchar(50)
- [x] Sightings
     - sighting_id int (PK)
     - user_id int (FK)
     - location_id int (FK)
     - cat_id int (FK)
     - img_path varchar(100)
     - sighting_description varchar(300)
     - disabled boolean
- [x] Locations
     - location_id int (PK)
     - latitude decimal(8,6)
     - longitude decimal(9,6)
- [x] Reports
     - report_id int (PK)
     - cat_id int (FK)
     - user_id int (FK)
     - sighting_id int (FK)
     - description varchar(300)

**Comment by see-k** [comment]
First Sprint Assignment

- [ ] User, Location: assigned to Chike
- [ ] Sightings, Cats: assigned to Quinn
- [ ] Alias, Reports: assigned to Derrick
