### ISSUE TITLE
Model Layer

### ISSUE THREAD

**Issue by dfidelman** [see-k/projectLasagna#19]
**Should be implemented prior to implementing any other layer
- [x] User class
- [x] Cat class
- [x] Sighting class
- [x] Report  class
- [x] Alias class
- [x] Location class

**Comment by see-k** [comment]
- [ ] User, Location: assigned to Chike
- [ ] Sightings, Cats: assigned to Quinn
- [ ] Alias, Reports: assigned to Derrick
