### ISSUE TITLE
Data.Mappers Layer 

### ISSUE THREAD

**Issue by dfidelman** [see-k/projectLasagna#22]
**To avoid conflicts, recommend completing prior to implementation of Repository classes**
- [x] UserMapper class
- [x] CatMapper class
- [x] SightingMapper class
- [x] ReportMapper class
- [x] LocationMapper class
- [x] AliasMapper class

**Comment by see-k** [comment]
- [ ] User, Location: assigned to Chike
- [ ] Sightings, Cats: assigned to Quinn
- [ ] Alias, Reports: assigned to Derrick
