### ISSUE TITLE
Data Layer - CatJdbcTemplateRepository

### ISSUE THREAD

**Issue by dfidelman** [see-k/projectLasagna#25]
**Should not be implemented until Data Layer - Interfaces have been completed**
- [ ] findAll( ) method
- [ ] findAllByUser( ) method
- [ ] findById( ) method
- [ ] add( ) method
- [ ] update( ) method
- [ ] deleteById( ) method
- [ ] addPictures( ) method
- [ ] addAliases( ) method

**Comment by see-k** [comment]
- [ ] Interface
