### ISSUE TITLE
Data Layer - SightingJdbcTemplateRepository

### ISSUE THREAD

**Issue by dfidelman** [see-k/projectLasagna#26]
**Should not be implemented until Data Layer - Interfaces have been completed**
- [ ] findAll( ) method
- [ ] findAllByUser( ) method
- [ ] findAllByCat( ) method
- [ ] findById( ) method
- [ ] add( ) method
- [ ] update( ) method
- [ ] deleteById( ) method
- [ ] addPictures( ) method
- [ ] addCats( ) method

**Comment by see-k** [comment]
- [ ] Interface
