### ISSUE TITLE
Data Layer - ReportJdbcTemplateRepository

### ISSUE THREAD

**Issue by dfidelman** [see-k/projectLasagna#28]
**Should not be implemented until Data Layer - Interfaces have been completed**
- [ ] findAll( ) method
- [ ] findAllByUserId( ) method
- [ ] findAllByCatId( ) method
- [ ] findById( ) method
- [ ] add( ) method
- [ ] update( ) method
- [ ] deleteById( ) method

**Comment by see-k** [comment]
- [ ] Report Interface
